language: go

go:
  - 1.8.x
  - 1.9.x
  - tip

before_install:
  - go get -v github.com/golang/lint/golint
  - go get -u github.com/kardianos/govendor

script:
  - govendor init
  - govendor fetch +o -v
  - go test `go list ./...|grep -v vendor`
  - golint `go list ./...|grep -v vendor`
  - govet `go list ./...|grep -v vendor`